// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrLJVO-4nExJES5muFjSkwDLfbtGHBiZ4',
    appId: '1:878908640419:web:63d9b1bc34636273f78316',
    messagingSenderId: '878908640419',
    projectId: 'movie-5db33',
    authDomain: 'movie-5db33.firebaseapp.com',
    storageBucket: 'movie-5db33.firebasestorage.app',
    measurementId: 'G-M4VFMWL5WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeTqIWHG6e1aNSxCttSRm5TTDCxkMi4HA',
    appId: '1:878908640419:android:03df7de7cfe9978ff78316',
    messagingSenderId: '878908640419',
    projectId: 'movie-5db33',
    storageBucket: 'movie-5db33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4zoZ-YOuzMnc4SDsj_As5SXFZBwXanMw',
    appId: '1:878908640419:ios:d4b9534ae9bab3a6f78316',
    messagingSenderId: '878908640419',
    projectId: 'movie-5db33',
    storageBucket: 'movie-5db33.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4zoZ-YOuzMnc4SDsj_As5SXFZBwXanMw',
    appId: '1:878908640419:ios:d4b9534ae9bab3a6f78316',
    messagingSenderId: '878908640419',
    projectId: 'movie-5db33',
    storageBucket: 'movie-5db33.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrLJVO-4nExJES5muFjSkwDLfbtGHBiZ4',
    appId: '1:878908640419:web:69d80cd25a6c8b17f78316',
    messagingSenderId: '878908640419',
    projectId: 'movie-5db33',
    authDomain: 'movie-5db33.firebaseapp.com',
    storageBucket: 'movie-5db33.firebasestorage.app',
    measurementId: 'G-9DB48PRWG2',
  );
}
